steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-south1-docker.pkg.dev/gen-lang-client-0767378085/image-registry/payments-mshyb",
        "-f",
        "dockerfile.prod",
        "--platform=linux/amd64",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-south1-docker.pkg.dev/gen-lang-client-0767378085/image-registry/payments-mshyb",
      ]
options:
  logging: CLOUD_LOGGING_ONLY